name: Deploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Initialize Terraform
      run: terraform init
      working-directory: .

    - name: Apply Terraform
      env:
        TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
        TF_VAR_server_ip: ${{ secrets.SERVER_IP }}
        TF_VAR_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      run: terraform apply -auto-approve
      working-directory: .